FILTERED_MIN_LEN = 30

OSU_DB_FILE = "osu!.db"
OSU_DB_SONGS = "Songs/"

SPEED_DECREASE_FACTOR_IN = 8
SPEED_DECREASE_FACTOR_OUT = SPEED_DECREASE_FACTOR_IN * 0.8
MIN_SNAP_SPEED = 0.5

POSSIBLE_SNAP_WINDOW_FACTOR = 0.6

ALLOWED_ERROR_FACTOR = 10

# Init core settings
MAX_NOTE_HOLD_TIME = 500
MIN_SLIDER_END_RELEASE_TIME = -300
MAX_SLIDER_END_RELEASE_TIME = 400

ROUND_DIGIT_COUNT = 2
EDGE_DISTANCE = 3
ADJUSTED_UR = False
