FILTERED_MIN_LEN = 30

MAX_NOTE_HOLD_TIME = 500

MIN_SLIDER_END_RELEASE_TIME = -300
MAX_SLIDER_END_RELEASE_TIME = 400

SLIDER_LIBRARY = "./.slider/"

OSU_DB_FILE = "osu!.db"
OSU_DB_SONGS = "Songs/"

SPEED_DECREASE_FACTOR = 8
FORCE_SNAP_DISTANCE = 1.4
MIN_SNAP_SPEED = 0.5
